<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLs2LlAd\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLs2LlAd/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLs2LlAd.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLs2LlAd\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLs2LlAd\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ls2LlAd',
    'container.build_id' => '02da3157',
    'container.build_time' => 1644019795,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLs2LlAd');
