<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTVxHSF5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTVxHSF5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTVxHSF5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTVxHSF5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTVxHSF5\App_KernelDevDebugContainer([
    'container.build_hash' => 'TVxHSF5',
    'container.build_id' => 'f8d26a1a',
    'container.build_time' => 1644016538,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTVxHSF5');
